In [1]:
# Importing modules
import pandas as pd
# NLP Processing
import nltk
nltk.download('popular')

[nltk_data] Downloading collection 'popular'
[nltk_data]    |
[nltk_data]    | Downloading package cmudict to
[nltk_data]    |     C:\Users\adri_\AppData\Roaming\nltk_data...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package gazetteers to
[nltk_data]    |     C:\Users\adri_\AppData\Roaming\nltk_data...
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to
[nltk_data]    |     C:\Users\adri_\AppData\Roaming\nltk_data...
[nltk_data]    |   Package genesis is already up-to-date!
[nltk_data]    | Downloading package gutenberg to
[nltk_data]    |     C:\Users\adri_\AppData\Roaming\nltk_data...
[nltk_data]    |   Package gutenberg is already up-to-date!
[nltk_data]    | Downloading package inaugural to
[nltk_data]    |     C:\Users\adri_\AppData\Roaming\nltk_data...
[nltk_data]    |   Package inaugural is already up-to-date!
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     C:\Users\adri_\AppData\Roaming\nltk_data...
[nltk_data]    |   Package movie_reviews is already up-to-date!
[nltk_data]    | Downloading package names to
[nltk_data]    |     C:\Users\adri_\AppData\Roaming\nltk_data...
[nltk_data]    |   Package names is already up-to-date!
[nltk_data]    | Downloading package shakespeare to
[nltk_data]    |     C:\Users\adri_\AppData\Roaming\nltk_data...
[nltk_data]    |   Package shakespeare is already up-to-date!
[nltk_data]    | Downloading package stopwords to
[nltk_data]    |     C:\Users\adri_\AppData\Roaming\nltk_data...
[nltk_data]    |   Package stopwords is already up-to-date!
[nltk_data]    | Downloading package treebank to
[nltk_data]    |     C:\Users\adri_\AppData\Roaming\nltk_data...
[nltk_data]    |   Package treebank is already up-to-date!
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     C:\Users\adri_\AppData\Roaming\nltk_data...
[nltk_data]    |   Package twitter_samples is already up-to-date!
[nltk_data]    | Downloading package omw to
[nltk_data]    |     C:\Users\adri_\AppData\Roaming\nltk_data...
[nltk_data]    |   Package omw is already up-to-date!
[nltk_data]    | Downloading package omw-1.4 to
[nltk_data]    |     C:\Users\adri_\AppData\Roaming\nltk_data...
[nltk_data]    |   Package omw-1.4 is already up-to-date!
[nltk_data]    | Downloading package wordnet to
[nltk_data]    |     C:\Users\adri_\AppData\Roaming\nltk_data...
[nltk_data]    |   Package wordnet is already up-to-date!
[nltk_data]    | Downloading package wordnet2021 to
[nltk_data]    |     C:\Users\adri_\AppData\Roaming\nltk_data...
[nltk_data]    |   Package wordnet2021 is already up-to-date!
[nltk_data]    | Downloading package wordnet31 to
[nltk_data]    |     C:\Users\adri_\AppData\Roaming\nltk_data...
[nltk_data]    |   Package wordnet31 is already up-to-date!
[nltk_data]    | Downloading package wordnet_ic to
[nltk_data]    |     C:\Users\adri_\AppData\Roaming\nltk_data...
[nltk_data]    |   Package wordnet_ic is already up-to-date!
[nltk_data]    | Downloading package words to
[nltk_data]    |     C:\Users\adri_\AppData\Roaming\nltk_data...
[nltk_data]    |   Package words is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     C:\Users\adri_\AppData\Roaming\nltk_data...
[nltk_data]    |   Package maxent_ne_chunker is already up-to-date!
[nltk_data]    | Downloading package punkt to
[nltk_data]    |     C:\Users\adri_\AppData\Roaming\nltk_data...
[nltk_data]    |   Package punkt is already up-to-date!
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     C:\Users\adri_\AppData\Roaming\nltk_data...
[nltk_data]    |   Package snowball_data is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     C:\Users\adri_\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    |
[nltk_data]  Done downloading collection popular

True

In [26]:
df1 = pd.read_csv('dataset2.csv')
df2 = pd.read_csv('positivo_limpio.csv')
df1.head()

,id,tweet,text_processed,class
0,"1,48236E+18",Fabin Sanabria no era el que por lambonearle a...,fabin sanabria lambonearle presidente santos a...,2
1,"1,48236E+18",la dualidad de una mujer de querer coquetearle...,dualidad mujer querer coquetearle mundo vez qu...,2
2,"1,48236E+18",No precisaron la edad de cuando se hizo cura ...,precisaron edad hizo cura l dijo lola varias n...,2
3,"1,48236E+18",Esta hija de un montonero y mujer de un camale...,hija montonero mujer camalen peronacho penosa ...,2
4,"1,48236E+18",Una mujer abierta a comprender y a tr...,mujer abierta comprender trabajar necesidades ...,0

In [27]:
new_df = pd.concat([df1,df2])
print(new_df.count())
new_df.head(230)

id                464
tweet             464
text_processed    463
class             464
dtype: int64

,id,tweet,text_processed,class
0,"1,48236E+18",Fabin Sanabria no era el que por lambonearle a...,fabin sanabria lambonearle presidente santos a...,2
1,"1,48236E+18",la dualidad de una mujer de querer coquetearle...,dualidad mujer querer coquetearle mundo vez qu...,2
2,"1,48236E+18",No precisaron la edad de cuando se hizo cura ...,precisaron edad hizo cura l dijo lola varias n...,2
3,"1,48236E+18",Esta hija de un montonero y mujer de un camale...,hija montonero mujer camalen peronacho penosa ...,2
4,"1,48236E+18",Una mujer abierta a comprender y a tr...,mujer abierta comprender trabajar necesidades ...,0
...,...,...,...,...
225,"1,48245E+18",Que hermosa putita me gustara como me gustara...,hermosa putita gustara gustara hacerte perra s...,1
226,"1,48243E+18",Que pesado sabe que meti la gamba y sigue......,pesado sabe meti gamba sigue culo sucioy perra...,1
227,"1,48246E+18",Se puede ser ms estupida No creo https://t.co/...,puede ser ms estupida creo,1
228,"1,48246E+18",No puede ser tan estpidaComo haces para cagar ...,puede ser tan estpidacomo haces cagar conversa...,1
229,"1,48244E+18",Por qu mierda la gente es tan estpida csm que ...,qu mierda gente tan estpida csm odio,1

In [28]:
"""import pandas as pd
import csv
data = pd.read_csv("ds.csv", sep=';') 
  
print("Original 'input.csv' CSV Data: \n") 
print(data) 
data.drop('id', inplace=True, axis=1) 

  
print("\nCSV Data after deleting the column 'year':\n") 
print(data)"""
new_df.to_csv('dataset2-of.csv', index=False, header=True, encoding="utf-8")
new_df.head()
new_df.count()

id                464
tweet             464
text_processed    463
class             464
dtype: int64

# uniendo 2

In [9]:
ds_1 = pd.read_csv('data_oficial/oficiales/oficial_completo_limpio.csv')
ds_2 = pd.read_csv('noviolentos2_mujer.csv')
ds_3 = pd.read_csv('data_oficial/oficiales/oficial_positivo_limpio.csv')

In [10]:

ds_3.count()

id                1038
tweet             1038
text_processed    1038
class             1038
dtype: int64

In [11]:
new_dataset = pd.concat([ds_1,ds_2,ds_3])
print(new_dataset.count())
new_dataset.head()

id                4044
tweet             4044
text_processed    4044
class             4044
dtype: int64

,id,tweet,text_processed,class
0,1,.pero ello viven ahi tambien y oleran la mierda,ello viven ahi tambien oleran mierda,1
1,2,Vieja fea horrible gritona,vieja fea horrible gritona,1
2,3,Amar es una mierda,amar mierda,1
3,4,Porque mierda existen personas tan posesivas y...,mierda existen persona tan posesivas caga verg...,1
4,5,carolina vos sos un alfiler mantenete alejada ...,carolina vos so alfiler mantenete alejada hace...,1

In [12]:
from sklearn.utils import shuffle
new_dataset = shuffle(new_dataset)

In [13]:
new_dataset.head(20)

,id,tweet,text_processed,class
93,97,te amo mas mi nina :(,amar ma ninar,0
188,189,No vayas provocando que luego desapareces y en...,vaya provocar luego desaparez espejo publico d...,1
449,450,Podre ser estupida pero no pendeja,podrir ser estupir pendeja,1
157,162,No tienen he ahi la respuesta :(,ahi respuesta,0
808,1451389290265600003,Balla se ala mierda Gorda #hijademilputa,ballo alo mierda gordo hijademilputo,1
831,1451348775042158595,"""Me da bronca la gente que esta todo el tiempo...",dar bronco gente tiempo flacar gordar tén culo...,1
144,149,mi amor :(,amor,0
5,6,Mi vieja no me fuma mas con la guitarra :((,viejo fuma ma guitarra,0
914,928,haci es Luis Daniel lo unico q podemos hacer e...,haci luis daniel unico q poder hacer pedir él ...,0
587,600,Pues este es Lush Queretaro... Pero ya llevenm...,pues lush queretaro llevenme casa,0
841,855,Y mi carro sigue afuera de su casa :( ya quier...,carro seguir afuero casa querer rojito componer,0
805,1451392215377268736,""" Quiero comerte el culo, estúpida perra, me t...",querer comerte culo estúpido perra pollar tant...,1
621,634,El Madrid de Mou :(,madrid mou,0
777,790,No lo hara :(((((,har,0
280,286,Y pensar q esta re lejos :(,pensar q re lejos,0
815,828,Jo veo cosas por Internet que me encantan y en...,jo ver cosa internet encantar encima mazo bara...,0
119,123,Mejor dicho odio no tener las copias :(.,mejor dicho odio tener copia,0
540,552,ay yo habia dejado de ver algunos y :(. Ame es...,ay habia dejado ver ame jasjskf,0
14,16,NO DEJEN DE VOTAR APARNTEMENTE ESTAMOS PERDIEN...,dejar votar aparntemente perder mtvhottest one...,0
540,549,Moraleja: todas las mujeres estis locas.,moralejar todo mujer esti loco,1

In [14]:
new_dataset.to_csv('semillero_prueba2.csv', index=False, header=True, encoding="utf-8")
new_dataset.count()

id                1880
tweet             1880
text_processed    1880
class             1880
dtype: int64

# UNIENDO varios YA EXISTENTES

In [110]:
ds_1 = pd.read_csv('data_oficial/empoderada_limpia.csv')
ds_2 = pd.read_csv('data_oficial/gas_limpia.csv')
ds_3 = pd.read_csv('data_oficial/felicitaciones_limpia.csv')
ds_4 = pd.read_csv('data_oficial/felicitacionesPresi_limpia.csv')
ds_5 = pd.read_csv('data_oficial/feliz_limpia.csv')
ds_6 = pd.read_csv('data_oficial/miracu_limpia.csv')
ds_7 = pd.read_csv('data_oficial/mujer_limpia.csv')
ds_8 = pd.read_csv('data_oficial/pena_limpia.csv')
ds_9 = pd.read_csv('data_oficial/peru_limpia.csv')
ds_10 = pd.read_csv('data_oficial/peru2_limpia.csv')
ds_11= pd.read_csv('data_oficial/seleccion_limpia.csv')

ds_4.count()

id                150
tweet             150
text_processed    150
class             150
dtype: int64

In [111]:
ds_1.drop(['class'], axis='columns', inplace=True)
ds_1["class"] = 0
ds_1.head(5)

,id,tweet,text_processed,class
0,1452153595701387266,"""RT : """"Pa Mis Muchachas"""" de ya esta disponi...",pa muchachas disponible unieron cuatro power l...,0
1,1452153438695985152,"""RT : Y ahora soy toda una gatita empoderada ,...",ahora toda gatita empoderada pasar sufrimiento...,0
2,1452150933329166339,Mulher empoderada q nem me responde no zap...E...,mulher empoderada q nem responde zapessas s q ...,0
3,1452150898977873920,Una vez que te sentis reina empoderada no te p...,vez sentis reina empoderada nadie amo,0
4,1452150490108735494,""" lana: ser una mujer empoderada, superaci...",lana ser mujer empoderada superacion acoso gla...,0

In [113]:
ds_2.drop(['class'], axis='columns', inplace=True)
ds_2["class"] = 0
ds_2.head(5)

,id,tweet,text_processed,class
0,1452300151738048518,#Politica: anuncia masificacion del Seguir ...,politica anuncia masificacion seguir leyendo p...,0
1,1452266124138074112,#Peru | El presidente anuncio la ampliacion d...,peru presidente anuncio ampliacion numero regi...,0
2,1452254915972243457,Que consorcio estara a cargo de desarrollar d...,consorcio estara cargo desarrollar dicha infra...,0
3,1452197082987696130,Bano realizado por TecnamBar Restaurante La Of...,bano realizado tecnambar restaurante oficinasa...,0
4,1452196819723821057,https://t.co/tVzrGk6Ldp#calefaccionportugalete...,calefaion sueloradiante aerotermia fontaneria ...,0

In [115]:
new_dataset = pd.concat([ds_1,ds_2,ds_3,ds_4,ds_6,ds_7,ds_8,ds_9,ds_10,ds_11])
print(new_dataset.count())

#new_dataset = new_dataset.dropna(axis=0, subset=['class'])
new_dataset.drop(['class'], axis='columns', inplace=True)
new_dataset["class"] = 0
new_dataset = new_dataset.dropna(axis=0, subset=['text_processed'])
#new_dataset['class'] = new_dataset['text_processed'].replace('1', np.nan)
new_dataset.count()

id                1038
tweet             1038
text_processed    1038
class             1038
dtype: int64

id                1038
tweet             1038
text_processed    1038
class             1038
dtype: int64

In [123]:
new_dataset.to_csv('data_oficial/oficiales/oficial_completo_limpio.csv', index=False, header=True, encoding="utf-8")
new_dataset.head()

,id,tweet,text_processed,class
0,1,.pero ello viven ahi tambien y oleran la mierda,ello viven ahi tambien oleran mierda,1
1,2,Vieja fea horrible gritona,vieja fea horrible gritona,1
2,3,Amar es una mierda,amar mierda,1
3,4,Porque mierda existen personas tan posesivas y...,mierda existen persona tan posesivas caga verg...,1
4,5,carolina vos sos un alfiler mantenete alejada ...,carolina vos so alfiler mantenete alejada hace...,1